import 'dotenv/config';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import express from 'express';
import { prisma } from '../lib/prisma';
import documentsRouter from './documents.routes';
import bootstrapRouter from './bootstrap.routes';
import { errorHandler } from '../middleware/errorHandling';
import { signAccessToken } from '../utils/jwt';
import { encryptDocumentOnBackend } from '../services/documentHybridEncryption';
import { createEncryptedTemporaryUpload } from '../services/documentFileStorage';
import { getStorageProvider, resetStorageProviderForTests } from '../infrastructure/storage/createStorageProvider';
import { FREE_STORAGE_LIMIT_BYTES as LIMIT, storedBytes } from '../services/accountUsage.service';

const userId = `usage-http-${crypto.randomUUID()}`;
async function run() {
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'readiness-quota-http-'));
  process.env.STORAGE_DRIVER = 'local'; process.env.LOCAL_STORAGE_PATH = directory;
  resetStorageProviderForTests();
  const app = express(); app.use(express.json()); app.use('/documents', documentsRouter); app.use('/api/bootstrap', bootstrapRouter); app.use(errorHandler);
  const server = app.listen(0, '127.0.0.1');
  await new Promise<void>(resolve => server.once('listening', resolve));
  const address = server.address() as { port: number };
  const token = signAccessToken({ sub: userId, email: `${userId}@example.invalid` });
  const request = (url: string, body?: unknown, method = body ? 'POST' : 'GET') => fetch(`http://127.0.0.1:${address.port}${url}`, { method, headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, ...(body ? { body: JSON.stringify(body) } : {}) });
  const pendingIds: string[] = [];
  const pendingPaths: string[] = [];
  const prepare = async (text: string) => {
    const envelope = encryptDocumentOnBackend(Buffer.from(text), { filename: 'page.png', mimeType: 'image/png' });
    const upload = await createEncryptedTemporaryUpload(userId, envelope);
    pendingIds.push(upload.id); pendingPaths.push(upload.storagePath);
    return upload;
  };
  const payload = (ids: string[]) => ({ tempFileIds: ids, category: 'Photo', documentType: 'Photo', confidence: 90, analysisSource: 'ai', fields: {} });
  try {
    await prisma.user.create({ data: { id: userId, name: 'Test', email: `${userId}@example.invalid` } });
    const first = await prepare('page one'); const second = await prepare('page two');
    const result = await request('/documents', payload([first.id, second.id]));
    assert.equal(result.status, 201, await result.clone().text());
    const { document } = await result.json();
    const files = await prisma.documentFile.findMany({ where: { documentId: document.id } });
    assert.equal(files.length, 2);
    assert.equal(await storedBytes(userId), first.encryptedSize! + second.encryptedSize!);
    for (const file of files) assert.equal(await getStorageProvider().exists(file.storageKey), true);
    assert.equal((await request(`/documents/${document.id}`, undefined, 'DELETE')).status, 204);
    assert.equal(await storedBytes(userId), 0);
    for (const file of files) assert.equal(await getStorageProvider().exists(file.storageKey), false, 'Delete removes every page');
    const blocked = await prepare('blocked');
    const filler = await prisma.document.create({ data: { ownerProfileId: userId, originalName: 'filler', storedName: 'filler', path: `${userId}/filler`, storageKey: `${userId}/filler`, size: LIMIT, encryptedSize: LIMIT, mimeType: 'image/png', documentType: 'photo', category: 'photo', analysisSource: 'user', confidence: 0, fields: {} } });
    const rejected = await request('/documents', { ...payload([blocked.id]), isPaid: true, accountTier: 'paid', size: 0 });
    assert.equal(rejected.status, 429);
    assert.equal((await rejected.json()).code, 'STORAGE_LIMIT_EXCEEDED');
    assert.equal(await prisma.document.count({ where: { ownerProfileId: userId } }), 1);
    assert.equal((await prisma.temporaryUpload.findUniqueOrThrow({ where: { id: blocked.id } })).consumedAt, null);
    await prisma.document.delete({ where: { id: filler.id } });
    const provider = getStorageProvider(); const originalUpload = provider.upload.bind(provider);
    let writes = 0;
    provider.upload = async input => { if (++writes === 2) throw new Error('Injected storage failure'); return originalUpload(input); };
    const third = await prepare('page three');
    const failed = await request('/documents', payload([blocked.id, third.id]));
    provider.upload = originalUpload;
    assert.equal(failed.status, 500);
    assert.equal(await prisma.document.count({ where: { ownerProfileId: userId } }), 0);
    assert.equal(await storedBytes(userId), 0);
    for (const id of [blocked.id, third.id]) assert.equal((await prisma.temporaryUpload.findUniqueOrThrow({ where: { id } })).consumedAt, null);
    const saved = await request('/documents', payload([blocked.id, third.id]));
    assert.equal(saved.status, 201, 'Retry after storage failure reuses intact temporary uploads');
    const body = await saved.json();
    const savedFiles = await prisma.documentFile.findMany({ where: { documentId: body.document.id } });
    const originalDelete = provider.delete.bind(provider);
    provider.delete = async () => { throw new Error('Injected deletion outage'); };
    assert.equal((await request(`/documents/${body.document.id}`, undefined, 'DELETE')).status, 204);
    assert.ok(await storedBytes(userId) > 0, 'Pending physical deletions remain accounted');
    provider.delete = originalDelete;
    const usage = await (await request('/api/bootstrap/usage')).json();
    assert.equal(usage.storage.usedBytes, 0, 'Usage refresh retries queued cleanup');
    for (const file of savedFiles) assert.equal(await provider.exists(file.storageKey), false);
    console.log('PASS: authenticated HTTP save/delete, multi-page bytes, forged paid bypass rejected before persistence, storage failure rollback/retry, cleanup outage accounting/retry.');
  } finally {
    await new Promise<void>(resolve => server.close(() => resolve()));
    await prisma.document.deleteMany({ where: { ownerProfileId: userId } });
    await prisma.temporaryUpload.deleteMany({ where: { id: { in: pendingIds } } });
    await prisma.user.deleteMany({ where: { id: userId } });
    await Promise.all(pendingPaths.map(file => fs.rm(file, { force: true })));
    await fs.rm(directory, { recursive: true, force: true });
    await prisma.$disconnect();
  }
}
run().catch(error => { console.error(error); process.exitCode = 1; });
